name: Security Gate Test

on:
  push:
    branches:
      - "test/**"

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  security-gate:
    name: Central Security Gate
    uses: TRM-MYOS/devsecops-security-platform/.github/workflows/security-scan.yml@main